version: '3.8'

networks:
  quasar:
    name: quasar

services:
  node:
    image: node:latest
    container_name: quasar_node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - quasar
  quasar:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "npx && quasar dev"
    networks:
      - quasar